In [2]:
#构造一个4*5的矩阵
import torch
z = torch.Tensor(4,5)
print(z)

tensor([[1.3563e-19, 1.3563e-19, 4.5071e+16, 2.4756e-12, 4.1183e-11],
        [1.1704e-19, 1.3563e-19, 1.3563e-19, 4.5071e+16, 2.4756e-12],
        [4.1411e-11, 1.1704e-19, 1.3563e-19, 1.3563e-19, 4.5071e+16],
        [2.4757e-12, 4.1638e-11, 8.1546e-33, 1.3563e-19, 1.6114e-19]])


In [2]:
#两个矩阵进行加法操作
y = torch.rand(4,5)#产生一个四行五列的矩阵
print(z+y)

tensor([[ 4.1236e-01,  6.3797e-01, -1.7420e+05,  5.8644e-01, -5.9358e+07],
        [ 3.0816e-01, -5.7443e+07,  7.4965e-01, -5.7444e+07,  3.8261e-01],
        [-5.7449e+07,  4.7479e-01, -5.7449e+07,  5.2457e-01, -5.7454e+07],
        [ 6.6048e-01, -5.7451e+07,  7.3850e-01, -5.7443e+07,  3.7736e-01]])


In [3]:
#矩阵加法的另一种表达形式
print(torch.add(z,y))

tensor([[ 4.1236e-01,  6.3797e-01, -1.7420e+05,  5.8644e-01, -5.9358e+07],
        [ 3.0816e-01, -5.7443e+07,  7.4965e-01, -5.7444e+07,  3.8261e-01],
        [-5.7449e+07,  4.7479e-01, -5.7449e+07,  5.2457e-01, -5.7454e+07],
        [ 6.6048e-01, -5.7451e+07,  7.3850e-01, -5.7443e+07,  3.7736e-01]])


In [4]:
#将Tensor转换为numpy数组
b = z.numpy()
print(b)

[[ 4.5656806e-37  4.5633284e-41 -1.7420100e+05  3.0759903e-41
  -5.9358272e+07]
 [ 4.5631883e-41 -5.7442560e+07  4.5631883e-41 -5.7443904e+07
   4.5631883e-41]
 [-5.7448512e+07  4.5631883e-41 -5.7449280e+07  4.5631883e-41
  -5.7454272e+07]
 [ 4.5631883e-41 -5.7451008e+07  4.5631883e-41 -5.7443328e+07
   4.5631883e-41]]


In [6]:
#将Numpy数组转化为Torch张量
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [11]:
#torch.squeeze(input,dim=None,out=None),将输入张量形状中的1去除并返回。当给定dim时，那么挤压操作只在给定维度上。
x = torch.zeros(2,1,2,1,2)
x.size()

torch.Size([2, 2, 1, 2])

In [12]:
y = torch.squeeze(x)
y.size()

torch.Size([2, 2, 2])

In [17]:
y = torch.squeeze(x,0)
y.size()

torch.Size([2, 1, 2, 1, 2])

In [14]:
y = torch.squeeze(x,1)
y.size()

torch.Size([2, 2, 1, 2])

In [3]:
#torch.abs(input,out=None),计算输入张量的每个元素的绝对值
torch.abs(torch.FloatTensor([-1,-2,3]))

tensor([1., 2., 3.])

In [4]:
#torch.acos(input,out=None),返回一个新的张量，包含输入张量每个元素的反余弦。

In [8]:
#torch.add(input,value,out=None),对输入张量input逐元素加上标量值value，并返回结果得到一个新的张量out
a = torch.randn(4)
print(a)
torch.add(a,20)

tensor([-1.8237, -1.9054,  0.2449,  1.9239])


tensor([18.1763, 18.0946, 20.2449, 21.9239])

In [12]:
#torch.mean(input),返回输入张量所有元素的均值
a = torch.randn(1,3)
print(a)
torch.mean(a)

tensor([[ 0.0704, -0.9960, -0.2251]])


tensor(-0.3836)

In [15]:
#torch.mean(input,dim,out=None),返回输入张量给定维度dim上每行的均值
a = torch.randn(4,4)
print(a)
torch.mean(a,dim=1)

tensor([[ 0.4417,  1.6805,  0.9165,  0.9715],
        [ 0.1796,  0.1889, -0.6740,  0.7853],
        [-0.9095, -0.2025, -1.4359,  0.4769],
        [-1.9075,  0.0790, -0.6905,  0.2836]])


tensor([ 1.0025,  0.1199, -0.5178, -0.5589])

In [18]:
torch.mean(a,dim=0)

tensor([-0.5489,  0.4364, -0.4710,  0.6293])

In [20]:
#torch.eq(input,other,out=None),比较元素的相等性。第二个参数可为一个数或与第一个参数同类型形状的张量
torch.eq(torch.Tensor([[1,2],[3,4]]),torch.Tensor([[1,1],[4,4]]))

tensor([[ True, False],
        [False,  True]])

In [22]:
#如果俩个张量有相同的形状和元素值，则返回True，否则False
torch.equal(torch.Tensor([[1,2],[3,4]]),torch.Tensor([[1,2],[3,4]]))

True

In [23]:
torch.ge(torch.Tensor([[1,2],[3,4]]),torch.Tensor([[1,1],[4,4]]))

tensor([[ True,  True],
        [False,  True]])

In [24]:
torch.gt(torch.Tensor([[1,2],[3,4]]),torch.Tensor([[1,1],[4,4]]))

tensor([[False,  True],
        [False, False]])